### ISSUE TITLE
Highlighting does not display

### ISSUE THREAD

**Issue by itzaeon** [nyngwang/murmur.lua#17] opened 2023-03-03 00:50 UTC
Hello! I can't seem to get this plugin to highlight anything. To reproduce, I used this config with nvim 0.8.3 from the AUR:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

vim.cmd('colorscheme blue')

local FOO = 'a_random_autogroup_name'
vim.api.nvim_create_augroup(FOO, { clear = true })

local plugins = {
    { "nyngwang/murmur.lua", lazy = false, config = function ()
	    require('murmur').setup {
	      -- cursor_rgb = {
	      --  guibg = '#393939',
	      -- },
	      -- cursor_rgb_always_use_config = false, -- if set to `true`, then always use `cursor_rgb`.
	      -- yank_blink = {
	      --   enabled = true,
	      --   on_yank = nil, -- Can be customized. See `:h on_yank`.
	      -- },
	      max_len = 80,
	      min_len = 3, -- this is recommended since I prefer no cursorword highlighting on `if`.
	      exclude_filetypes = {},
	      callbacks = {
		-- to trigger the close_events of vim.diagnostic.open_float.
		function ()
		  -- Close floating diag. and make it triggerable again.
		  vim.cmd('doautocmd InsertEnter')
		  vim.w.diag_shown = false
		end,
	      }
	    }

	    -- To create IDE-like no blinking diagnostic message with `cursor` scope. (should be paired with the callback above)
	    vim.api.nvim_create_autocmd({ 'CursorHold' }, {
	      group = FOO,
	      pattern = '*',
	      callback = function ()
		-- skip when a float-win already exists.
		if vim.w.diag_shown then return end

		-- open float-win when hovering on a cursor-word.
		if vim.w.cursor_word ~= '' then
		  vim.diagnostic.open_float()
		  vim.w.diag_shown = true
		end
	      end
	    })

	    -- To create special cursorword coloring for the colortheme `typewriter-night`.
	    -- remember to change it to the name of yours.
	    vim.api.nvim_create_autocmd({ 'ColorScheme' }, {
	      group = FOO,
	      pattern = 'blue',
	      callback = function ()
		vim.api.nvim_set_hl(0, "murmur_cursor_rgb", { fg = "#0a100d", bg = "#ffee32" })
	      end
	    })
	  end
	}
}
require("lazy").setup(plugins)
```

I have verified that `murmur.lua` is loaded in the `:Lazy` dialog. I believe I've done everything for the plugin to highlight. Let me know if you need more information on something. Thanks!

**Comment by nyngwang** [comment] 2023-03-05 23:32
@itzaeon Sorry for my late reply. Yup, I can reproduce the problem you pointed out with the minimal script you provided. Apparently*, you will have to call `vim.cmd('colorscheme blue')` **after** your last line `require("lazy").setup(plugins)`.


*: In fact, it took me a while to identify the cause :P

**Comment by itzaeon** [comment] 2023-03-06 17:07
I ended up using [rebelot/heirline.nvim](https://github.com/rebelot/heirline.nvim)'s function ``get_highlight`` like so:
```lua
	    vim.api.nvim_create_autocmd({ 'ColorScheme' }, {
	      group = FOO,
	      pattern = '*',
	      callback = function ()
                local fore = require('heirline.utils').get_highlight("Normal").fg
                local back = require('heirline.utils').get_highlight("Folded").bg
		vim.api.nvim_set_hl(0, "murmur_cursor_rgb", { fg = fore, bg = back })
	      end
	    })
```

Thanks for the tip!

**Comment by nyngwang** [comment] 2023-03-06 18:09
@itzaeon Great! [rebelot/heirline.nvim](https://github.com/rebelot/heirline.nvim) is indeed a great plugin that has abundant documentation on detailed customization. Closing but feel free to reopen if the problem persists.

**Closed by nyngwang** 2023-03-06 18:09 UTC
Labels: documentation, Roger that
